export const OWASP_TOP_10 = [
  {
    id: 'A01:2021',
    name: 'Broken Access Control',
    description: 'Restrictions on authenticated users are not properly enforced. Attackers can exploit flaws to access unauthorized functionality and/or data.',
    cwes: ['CWE-200', 'CWE-201', 'CWE-352', 'CWE-276', 'CWE-285', 'CWE-639', 'CWE-862', 'CWE-863'],
    impact: 'critical',
    testCases: [
      'Bypass access control checks by modifying URL, application state, or HTML page',
      'Allowing primary key to be changed to another user\'s record (IDOR)',
      'Elevation of privilege (acting as user without login, or as admin when logged in as user)',
      'Metadata manipulation (replaying or tampering with JWT, cookie, or hidden field)',
      'CORS misconfiguration allows unauthorized API access',
      'Force browsing to authenticated pages or privileged pages',
    ],
  },
  {
    id: 'A02:2021',
    name: 'Cryptographic Failures',
    description: 'Failures related to cryptography which often lead to exposure of sensitive data. Previously known as Sensitive Data Exposure.',
    cwes: ['CWE-259', 'CWE-327', 'CWE-331', 'CWE-328', 'CWE-916'],
    impact: 'high',
    testCases: [
      'Data transmitted in clear text (HTTP, SMTP, FTP)',
      'Old or weak cryptographic algorithms or protocols used',
      'Default crypto keys used, weak keys generated or re-used',
      'Encryption not enforced (missing security directives or headers)',
      'Server certificate not validated or trusted',
      'Passwords stored using reversible encryption or weak hashing',
    ],
  },
  {
    id: 'A03:2021',
    name: 'Injection',
    description: 'User-supplied data is not validated, filtered, or sanitized. Dynamic queries or non-parameterized calls used without context-aware escaping.',
    cwes: ['CWE-79', 'CWE-89', 'CWE-73', 'CWE-77', 'CWE-78', 'CWE-917'],
    impact: 'critical',
    testCases: [
      'SQL injection via unparameterized queries',
      'NoSQL injection',
      'OS command injection',
      'LDAP injection',
      'Expression Language / OGNL injection',
      'Cross-site scripting (XSS) - Reflected, Stored, DOM-based',
      'Server-side template injection (SSTI)',
    ],
  },
  {
    id: 'A04:2021',
    name: 'Insecure Design',
    description: 'Missing or ineffective control design. Different from implementation bugs—it\'s about flaws in the design itself.',
    cwes: ['CWE-209', 'CWE-256', 'CWE-501', 'CWE-522'],
    impact: 'high',
    testCases: [
      'Missing rate limiting on sensitive functionality',
      'Insufficient bot or automated attack protection',
      'Missing trust boundaries in data flow',
      'Lack of segregation of tenancy',
      'Business logic flaws (negative quantity, race conditions)',
      'Missing threat modeling for critical flows',
    ],
  },
  {
    id: 'A05:2021',
    name: 'Security Misconfiguration',
    description: 'Missing security hardening, improperly configured permissions, unnecessary features enabled, default accounts unchanged.',
    cwes: ['CWE-16', 'CWE-611', 'CWE-1004'],
    impact: 'high',
    testCases: [
      'Unnecessary features enabled (ports, services, pages, accounts, privileges)',
      'Default accounts/passwords still enabled and unchanged',
      'Error handling reveals stack traces or overly informative error messages',
      'Security features disabled or not configured in upgraded systems',
      'Security settings in app servers/frameworks/libraries/databases not set to secure values',
      'Missing or misconfigured security headers (HSTS, CSP, X-Frame-Options)',
      'Missing appropriate CORS policy',
    ],
  },
  {
    id: 'A06:2021',
    name: 'Vulnerable and Outdated Components',
    description: 'Using components with known vulnerabilities. Lack of version awareness, vulnerability scanning, and patch management.',
    cwes: ['CWE-1104'],
    impact: 'high',
    testCases: [
      'Known vulnerable versions of OS, web/application server, DBMS, APIs, runtime environments',
      'Known vulnerable client-side or server-side libraries and dependencies',
      'Components no longer maintained or supported',
      'Missing regular vulnerability scanning (Snyk, Dependabot, etc.)',
      'Components not sourced from official channels over secured links',
    ],
  },
  {
    id: 'A07:2021',
    name: 'Identification and Authentication Failures',
    description: 'Confirmation of user identity, authentication, and session management failures. Previously Broken Authentication.',
    cwes: ['CWE-255', 'CWE-259', 'CWE-287', 'CWE-288', 'CWE-290', 'CWE-294', 'CWE-295', 'CWE-297'],
    impact: 'critical',
    testCases: [
      'Permits automated attacks (credential stuffing, brute force)',
      'Permits default, weak, or well-known passwords',
      'Uses weak credential recovery (knowledge-based answers)',
      'Uses plain text, encrypted, or weakly hashed password data stores',
      'Missing or ineffective multi-factor authentication',
      'Exposes session identifier in URL',
      'Reuses session identifier after successful login',
      'Does not properly invalidate sessions on logout/inactivity',
    ],
  },
  {
    id: 'A08:2021',
    name: 'Software and Data Integrity Failures',
    description: 'Code and infrastructure that does not protect against integrity violations. Insecure CI/CD pipeline, auto-update without integrity verification.',
    cwes: ['CWE-345', 'CWE-353', 'CWE-426', 'CWE-494', 'CWE-502', 'CWE-565', 'CWE-784'],
    impact: 'high',
    testCases: [
      'Plugins, libraries, or modules from untrusted sources, repos, and CDNs',
      'Insecure CI/CD pipeline introducing unauthorized access or malicious code',
      'Auto-update functionality downloading without sufficient integrity verification',
      'Insecure deserialization (objects or data from untrusted sources)',
      'Missing code signing or supply chain verification',
    ],
  },
  {
    id: 'A09:2021',
    name: 'Security Logging and Monitoring Failures',
    description: 'Without logging and monitoring, breaches cannot be detected. Insufficient logging, detection, monitoring, and active response.',
    cwes: ['CWE-117', 'CWE-223', 'CWE-532', 'CWE-778'],
    impact: 'medium',
    testCases: [
      'Auditable events (logins, failed logins, high-value transactions) are not logged',
      'Warnings and errors generate no, inadequate, or unclear log messages',
      'Logs of applications and APIs are not monitored for suspicious activity',
      'Logs are only stored locally',
      'Alerting thresholds and response escalation processes are not in place',
      'Penetration testing and scans by DAST tools do not trigger alerts',
    ],
  },
  {
    id: 'A10:2021',
    name: 'Server-Side Request Forgery',
    description: 'SSRF flaws occur when a web application fetches a remote resource without validating the user-supplied URL.',
    cwes: ['CWE-918'],
    impact: 'high',
    testCases: [
      'Fetching URL without validating user-supplied destination',
      'Internal service access via manipulated URLs',
      'Cloud metadata service access (169.254.169.254)',
      'Internal port scanning via URL manipulation',
      'Access to internal admin interfaces via URL redirects',
      'Protocol smuggling (file://, dict://, gopher://)',
    ],
  },
]

export const KILL_CHAIN_PHASES = [
  { id: 'reconnaissance', name: 'Reconnaissance', description: 'Target identification, OSINT gathering, footprinting, and passive/active enumeration', icon: 'search', color: '#3b82f6' },
  { id: 'weaponization', name: 'Weaponization', description: 'Developing attack tools, creating exploits, and preparing payloads specific to discovered vulnerabilities', icon: 'wrench', color: '#8b5cf6' },
  { id: 'delivery', name: 'Delivery', description: 'Transmitting the weaponized payload to the target via web, email, USB, or other vectors', icon: 'send', color: '#f97316' },
  { id: 'exploitation', name: 'Exploitation', description: 'Triggering the exploit to gain unauthorized access, execute code, or compromise the target system', icon: 'zap', color: '#ef4444' },
  { id: 'installation', name: 'Installation', description: 'Establishing persistence through backdoors, rootkits, web shells, or scheduled tasks', icon: 'download', color: '#ec4899' },
  { id: 'command_control', name: 'Command & Control', description: 'Establishing a communication channel for remote control of the compromised system', icon: 'radio', color: '#14b8a6' },
  { id: 'actions', name: 'Actions on Objectives', description: 'Achieving the adversary\'s goal: data exfiltration, destruction, or lateral movement', icon: 'target', color: '#eab308' },
]

export const MITRE_TACTICS = [
  { id: 'TA0043', name: 'Reconnaissance', color: '#3b82f6' },
  { id: 'TA0042', name: 'Resource Development', color: '#6366f1' },
  { id: 'TA0001', name: 'Initial Access', color: '#8b5cf6' },
  { id: 'TA0002', name: 'Execution', color: '#a855f7' },
  { id: 'TA0003', name: 'Persistence', color: '#d946ef' },
  { id: 'TA0004', name: 'Privilege Escalation', color: '#ec4899' },
  { id: 'TA0005', name: 'Defense Evasion', color: '#f43f5e' },
  { id: 'TA0006', name: 'Credential Access', color: '#ef4444' },
  { id: 'TA0007', name: 'Discovery', color: '#f97316' },
  { id: 'TA0008', name: 'Lateral Movement', color: '#eab308' },
  { id: 'TA0009', name: 'Collection', color: '#84cc16' },
  { id: 'TA0011', name: 'Command and Control', color: '#22c55e' },
  { id: 'TA0010', name: 'Exfiltration', color: '#14b8a6' },
  { id: 'TA0040', name: 'Impact', color: '#06b6d4' },
]

export const COMPLIANCE_FRAMEWORKS = [
  {
    id: 'pci_dss',
    name: 'PCI DSS 4.0',
    fullName: 'Payment Card Industry Data Security Standard',
    requirements: [
      { id: '1', name: 'Install and maintain network security controls', category: 'Build and Maintain a Secure Network' },
      { id: '2', name: 'Apply secure configurations to all system components', category: 'Build and Maintain a Secure Network' },
      { id: '3', name: 'Protect stored account data', category: 'Protect Account Data' },
      { id: '4', name: 'Protect cardholder data with strong cryptography during transmission', category: 'Protect Account Data' },
      { id: '5', name: 'Protect all systems and networks from malicious software', category: 'Maintain a Vulnerability Management Program' },
      { id: '6', name: 'Develop and maintain secure systems and software', category: 'Maintain a Vulnerability Management Program' },
      { id: '7', name: 'Restrict access to system components and cardholder data by business need to know', category: 'Implement Strong Access Control Measures' },
      { id: '8', name: 'Identify users and authenticate access to system components', category: 'Implement Strong Access Control Measures' },
      { id: '9', name: 'Restrict physical access to cardholder data', category: 'Implement Strong Access Control Measures' },
      { id: '10', name: 'Log and monitor all access to system components and cardholder data', category: 'Regularly Monitor and Test Networks' },
      { id: '11', name: 'Test security of systems and networks regularly', category: 'Regularly Monitor and Test Networks' },
      { id: '12', name: 'Support information security with organizational policies and programs', category: 'Maintain an Information Security Policy' },
    ],
  },
  {
    id: 'owasp',
    name: 'OWASP Top 10',
    fullName: 'Open Worldwide Application Security Project Top 10 - 2021',
    requirements: OWASP_TOP_10.map((item) => ({
      id: item.id,
      name: item.name,
      category: 'Application Security',
    })),
  },
  {
    id: 'hipaa',
    name: 'HIPAA',
    fullName: 'Health Insurance Portability and Accountability Act',
    requirements: [
      { id: '164.312(a)(1)', name: 'Access Control', category: 'Technical Safeguards' },
      { id: '164.312(a)(2)(i)', name: 'Unique User Identification', category: 'Technical Safeguards' },
      { id: '164.312(a)(2)(iii)', name: 'Automatic Logoff', category: 'Technical Safeguards' },
      { id: '164.312(a)(2)(iv)', name: 'Encryption and Decryption', category: 'Technical Safeguards' },
      { id: '164.312(b)', name: 'Audit Controls', category: 'Technical Safeguards' },
      { id: '164.312(c)(1)', name: 'Integrity', category: 'Technical Safeguards' },
      { id: '164.312(d)', name: 'Person or Entity Authentication', category: 'Technical Safeguards' },
      { id: '164.312(e)(1)', name: 'Transmission Security', category: 'Technical Safeguards' },
    ],
  },
  {
    id: 'soc2',
    name: 'SOC 2',
    fullName: 'System and Organization Controls 2',
    requirements: [
      { id: 'CC6.1', name: 'Logical and Physical Access Controls', category: 'Common Criteria' },
      { id: 'CC6.2', name: 'User Registration and Authorization', category: 'Common Criteria' },
      { id: 'CC6.3', name: 'Role-Based Access and Least Privilege', category: 'Common Criteria' },
      { id: 'CC6.6', name: 'System Boundary Protection', category: 'Common Criteria' },
      { id: 'CC6.7', name: 'Data Transmission Restriction', category: 'Common Criteria' },
      { id: 'CC6.8', name: 'Malicious Software Prevention', category: 'Common Criteria' },
      { id: 'CC7.1', name: 'Vulnerability and Threat Detection', category: 'Common Criteria' },
      { id: 'CC7.2', name: 'Anomaly and Event Monitoring', category: 'Common Criteria' },
      { id: 'CC7.3', name: 'Security Incident Evaluation', category: 'Common Criteria' },
      { id: 'CC8.1', name: 'Change Management Controls', category: 'Common Criteria' },
    ],
  },
  {
    id: 'iso27001',
    name: 'ISO 27001',
    fullName: 'ISO/IEC 27001:2022 Information Security Management',
    requirements: [
      { id: 'A.5', name: 'Organizational Controls', category: 'Annex A Controls' },
      { id: 'A.6', name: 'People Controls', category: 'Annex A Controls' },
      { id: 'A.7', name: 'Physical Controls', category: 'Annex A Controls' },
      { id: 'A.8', name: 'Technological Controls', category: 'Annex A Controls' },
      { id: 'A.8.5', name: 'Secure Authentication', category: 'Technological Controls' },
      { id: 'A.8.9', name: 'Configuration Management', category: 'Technological Controls' },
      { id: 'A.8.12', name: 'Data Leakage Prevention', category: 'Technological Controls' },
      { id: 'A.8.16', name: 'Monitoring Activities', category: 'Technological Controls' },
      { id: 'A.8.24', name: 'Use of Cryptography', category: 'Technological Controls' },
      { id: 'A.8.25', name: 'Secure Development Life Cycle', category: 'Technological Controls' },
      { id: 'A.8.28', name: 'Secure Coding', category: 'Technological Controls' },
    ],
  },
]

export const CVSS_V3_METRICS = {
  attackVector: { label: 'Attack Vector (AV)', options: [
    { value: 'N', label: 'Network', score: 0.85 },
    { value: 'A', label: 'Adjacent', score: 0.62 },
    { value: 'L', label: 'Local', score: 0.55 },
    { value: 'P', label: 'Physical', score: 0.20 },
  ]},
  attackComplexity: { label: 'Attack Complexity (AC)', options: [
    { value: 'L', label: 'Low', score: 0.77 },
    { value: 'H', label: 'High', score: 0.44 },
  ]},
  privilegesRequired: { label: 'Privileges Required (PR)', options: [
    { value: 'N', label: 'None', score: 0.85, scopeChanged: 0.85 },
    { value: 'L', label: 'Low', score: 0.62, scopeChanged: 0.68 },
    { value: 'H', label: 'High', score: 0.27, scopeChanged: 0.50 },
  ]},
  userInteraction: { label: 'User Interaction (UI)', options: [
    { value: 'N', label: 'None', score: 0.85 },
    { value: 'R', label: 'Required', score: 0.62 },
  ]},
  scope: { label: 'Scope (S)', options: [
    { value: 'U', label: 'Unchanged' },
    { value: 'C', label: 'Changed' },
  ]},
  confidentiality: { label: 'Confidentiality (C)', options: [
    { value: 'H', label: 'High', score: 0.56 },
    { value: 'L', label: 'Low', score: 0.22 },
    { value: 'N', label: 'None', score: 0 },
  ]},
  integrity: { label: 'Integrity (I)', options: [
    { value: 'H', label: 'High', score: 0.56 },
    { value: 'L', label: 'Low', score: 0.22 },
    { value: 'N', label: 'None', score: 0 },
  ]},
  availability: { label: 'Availability (A)', options: [
    { value: 'H', label: 'High', score: 0.56 },
    { value: 'L', label: 'Low', score: 0.22 },
    { value: 'N', label: 'None', score: 0 },
  ]},
}

export const SEVERITY_THRESHOLDS = {
  none: { min: 0, max: 0, color: '#6b7280', bg: 'bg-gray-500' },
  low: { min: 0.1, max: 3.9, color: '#3b82f6', bg: 'bg-blue-500' },
  medium: { min: 4.0, max: 6.9, color: '#eab308', bg: 'bg-yellow-500' },
  high: { min: 7.0, max: 8.9, color: '#f97316', bg: 'bg-orange-500' },
  critical: { min: 9.0, max: 10.0, color: '#ef4444', bg: 'bg-red-500' },
}

export const SCAN_PHASES = [
  'reconnaissance',
  'scanning',
  'enumeration',
  'exploitation',
  'post_exploitation',
  'reporting',
]

export const TARGET_TYPES = [
  { value: 'web_application', label: 'Web Application', icon: 'globe' },
  { value: 'api', label: 'API', icon: 'code' },
  { value: 'network', label: 'Network', icon: 'network' },
  { value: 'mobile_api', label: 'Mobile API', icon: 'smartphone' },
  { value: 'cloud_infrastructure', label: 'Cloud Infrastructure', icon: 'cloud' },
]

export const SCAN_MODES = [
  { value: 'quick', label: 'Quick Scan', desc: '~15 min. Surface-level vulnerability assessment with passive checks.', color: '#3b82f6', intensity: 1 },
  { value: 'standard', label: 'Standard', desc: '1-2 hrs. Comprehensive scanning with active vulnerability testing.', color: '#10b981', intensity: 2 },
  { value: 'deep', label: 'Deep Scan', desc: '4-8 hrs. Thorough testing with exploit validation and chaining.', color: '#f97316', intensity: 3 },
  { value: 'continuous', label: 'Continuous', desc: 'Recurring scheduled scans. Monitors for new vulnerabilities over time.', color: '#8b5cf6', intensity: 4 },
  { value: 'red_team', label: 'Red Team', desc: 'Full adversarial simulation with advanced evasion and persistence testing.', color: '#ef4444', intensity: 5 },
]

export const VULNERABILITY_CATEGORIES = [
  { id: 'injection', name: 'Injection Flaws', severity: 'critical', types: ['SQL Injection', 'NoSQL Injection', 'OS Command Injection', 'LDAP Injection', 'XML Injection', 'SSTI'] },
  { id: 'xss', name: 'Cross-Site Scripting', severity: 'high', types: ['Reflected XSS', 'Stored XSS', 'DOM-Based XSS', 'Mutation XSS'] },
  { id: 'auth', name: 'Authentication Flaws', severity: 'critical', types: ['Brute Force', 'Credential Stuffing', 'Session Fixation', 'Weak Passwords', 'Missing MFA'] },
  { id: 'access', name: 'Access Control', severity: 'critical', types: ['IDOR', 'Privilege Escalation', 'Path Traversal', 'Force Browsing', 'CORS Misconfiguration'] },
  { id: 'crypto', name: 'Cryptographic Issues', severity: 'high', types: ['Weak Cipher', 'Missing TLS', 'Insecure Key Storage', 'Weak Hashing', 'Certificate Issues'] },
  { id: 'ssrf', name: 'Server-Side Request Forgery', severity: 'high', types: ['Internal Access', 'Cloud Metadata', 'Protocol Smuggling', 'DNS Rebinding'] },
  { id: 'misconfig', name: 'Misconfigurations', severity: 'medium', types: ['Debug Mode', 'Default Credentials', 'Missing Headers', 'Directory Listing', 'Error Disclosure'] },
  { id: 'components', name: 'Vulnerable Components', severity: 'high', types: ['Outdated Libraries', 'Known CVEs', 'Unmaintained Dependencies', 'Supply Chain'] },
  { id: 'api', name: 'API Security', severity: 'high', types: ['Broken Object Level Auth', 'Excessive Data Exposure', 'Lack of Rate Limiting', 'Mass Assignment', 'Improper Inventory'] },
  { id: 'business', name: 'Business Logic', severity: 'medium', types: ['Race Conditions', 'Price Manipulation', 'Feature Abuse', 'Workflow Bypass'] },
]
